### ISSUE TITLE
Alternate APIs for 6.0

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-element#47]
For 6.0, there's a few ideas we might want to consider / test:

## Remove the `define`

Many of our guides and examples could be built without much in the way of the `define` object.  We could create a `StacheElement` that was just the proxy and stache:

```js
class MyCounter extends StacheElement {
  static view = `Count: {{this.count}} <button on:click="this.increment()">+1</button>`;
  count = 0;
  increment(){
    this.count++;
  }
}
```

For models, we'd only _really_ need to support identity for it to work.  We could do that in other ways possibly:

```js
class Todo extends ObservableObject {
  static identity = "id";
}
```

Pros:

- This should be relatively easy to build as everything is more-or-less written as independent mixins.
- This might make "core" CanJS lighterweight.  Maybe drop it ~8k?
- `StacheDefineElement` is so wordy.  `StacheElement` feels a lot nicer to type over and over and over.

Cons:

- Any real-world app is going to want something more.  They would quickly want to move to `StacheDefineElement` and `DefineObject`.  
- How would this work with can-query-logic

Alternatives:

- We could rename to `StacheElement` and `ObservableObject`, but just keep the `define` ability.

## Props and state

Being easily able to distinguish between "internal" and "external" stateful values on components is really nice. In the logic guide, we encourage people to group their properties as "internal" and "external" properties.  React has done this with `props` and `state`. I think Vue does something similar.

It might be useful to enable this. For example:

```js
class MyWidget extends StacheDefineElement {
  static props = {
    dataId: Number
  };

  static state = {
    data: { async(){ return Data.get(this.dataId) } }
  };
}
```

We could make only `props` accessible to `can-stache-bindings`.  Changing or reading a `state` property would result in an error.

We could also change `DefineObject` to use `props` as all of these properties would be available to bindings.

Implementation:

- These properties would probably need some special flag that `can-stache-bindings` knows about.

Pros:

- Force people to organize their code to clearly indicate what is exposed and what is not.

Cons:

- We can't really enforce setting the state as these would still be properties on the element. This would only be protection through CanJS's apis.

## Hide the define, call it props and state

A combo proposal!  We could combine the above two proposals. We'd:

- Call things `StacheElement` and `ObservableObject`
- `StacheElement` and `ObservableObject` would use `props` instead of `define`, but they would have all the existing abilities.
- `StacheElement` could eventually add `state`.

#### Pros:

I think the following looks a bit nicer:

```js
class MyCounter extends StacheElement {
  static view = `Count: {{this.count}} <button on:click="this.increment()">+1</button>`;
  count = 0;
  increment(){
    this.count++;
  }
}
```

And then people do:

```js
class MyCounter extends StacheElement {
  static view = `Count: {{this.count}} <button on:click="this.increment()">+1</button>`;

  static props = {
    count: {type: Number, default: 0};
  };
  
  increment(){
    this.count++;
  }
}
```

`props` is going to fit with react folks better.  Also, `Define` and `define` together just feel a bit odd after using it.

#### Cons:

- As it includes define behavior, this isn't as lightweight as removing things all together.
- Calling it `StacheElement`, while including the define behavior, makes this Element the default.  However, we might want other state mechanisms.

**Comment by Mattchewone** [comment]
EDIT:

I should have been more thorough with my reading of the initial document..

--- 

Would having a `props` property mean that you can only write to the defined `props`?

```js
class MyWidget extends StacheDefineElement {
  static props = {
    firstName: String,
    lastName: String
  };

  static state = {
    fullName: {
      get () {
        return `${this.firstName} ${this.lastName}`
      }
    }
  };
}

<MyWidget firstName="Justin" lastName="Meyer" fullName="Bob Smith" /> //=> Justin Meyer
```

**Comment by phillipskevin** [comment]
Something I've been thinking about is what if we simplified the `define` (or `props`, whatever we want to call it), so that it doesn't take a `DefinitionObject`. I think one thing people find really confusing is the multiple ways to do the same thing (like types and defaults). This would mean that we only allow "single behavior" properties:

```js
static props = {
  age: 72,
  count: Number,
  birthday: Date,
  name: type.maybe(String),
  header: stache('<h1>{{name}}</h1>`),
  get excitedName() {
    return `${this.name}!!`;
  }
}
```

What would we be losing if we did not support multiple behaviors? Here is a list:

- combination of `type` and `default`
- setters with > 1 arg
- async getters
- getters using `lastSetValue`
- enumerable
- non-primitive defaults
- identity
- required
- serialize
- value

This seems like a lot, but most of these things aren't used very often. Things like `enumerable`, `identity`, `required` could be handled using other `static` properties like `static requiredProps = [ "name" ];`

I think async getters and `value` are the biggest losses.

One idea to support these is create another type similar to `TypeObject` (I'll call it `DefineObject` below) that has some Symbols that would tell `can-define-mixin` how to set up the getter/setter pair for this property and handle any setup/teardown. This would mean instead of an object with an `async` property, the property would point to the value returned by an `asyncGet` helper that creates this `DefineObject` type:

```js
import { DefineObject, asyncGet, resolver } from "can/everything";

class AppViewModel extends DefineObject {
  static define = {
    customerId: Number,
    // this uses an `asyncGet` function that creates a DefineObject type that has
    // specific Symbols that DefineObject understands
    customer: asyncGet(function(resolve) {
        Customer.get({ id: this.customerId })
          .then(customer => {
            resolve(customer);
          });
    }),

    name: String,
    // this uses a `resolver` function that creates a DefineObject type that has
    // specific Symbols that DefineObject understands
    nameChangeCount: resolver(function({ listenTo, resolve }) {
        let count = 0;
        listenTo( "name", () => resolve( ++count ) );
        resolve( count );
    })
  };
}
```

A side benefit of this is that `can-define-mixin` would only need the logic for handling this standardized `DefineObject` type and the logic specific to `value` for example, could be moved to the `resolver` function. This would mean if you're not using `resolver`, `AsyncObservable` and all the other logic needed for this could be tree-shaken.

**Comment by chasenlehara** [comment]
I like this idea. I wonder 1) how would something like can-validate be implemented in this system and 2) are there any runtime performance implications?

**Comment by phillipskevin** [comment]
We've settled on `props` for 6.0 and opened #122 to investigate the API I proposed. Going to close this. We can revisit separating out `state` as we do user testing.
